### ISSUE TITLE
运行exe报错 

### ISSUE THREAD

**Issue by zcx761105** [LunarConcerto/MRT#10]
java.lang.ClassNotFoundException: com.github.lunarconcerto.mrt.MRTStarter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)

**Comment by qianchencc** [comment]
上甲骨文安装最新版的jdk，直接在bing上搜到的java版本是java8的，版本太低了

**Comment by qianchencc** [comment]
奇怪的是运行jar可以正常使用但是没法保存记录，运行主文件还是会报错
